
groups:
  latin_A: AÀÁÂÃÄÅĀĂĄǍǞǠǺȀȂȦḀẠẢẤẦẨẪẬẮẰẲẴẶɅ
  latin_Æ: ÆǢǼ
  latin_F: FƑḞ
  latin_L: LĹĻĽĿŁȽḶḸḺḼ
  latin_P: PṔṖ
  latin_T: TŢŤŦȚṪṬṮṰ
  latin_Ư: ƯỨỪỬỮỰ
  latin_V: VṼṾⱯ
  latin_W: WŴẀẂẄẆẈ
  latin_Y: YÝŶŸȲẎỲỴỶỸ
  latin_a: aàáâãäåæāăąǎǟǡǣǻǽȁȃȧḁẚạảấầẩẫậắằẳẵặ
  latin_cemnosuxz: cçćĉċčḉeèéêëēĕėęěǝȅȇȩḕḗḙḛḝẹẻẽếềểễệĸmḿṁṃnñńņňŉŋǌǹṅṇṉṋoòóôõöøōŏőœǒǫǭǿȍȏȫȭȯȱṍṏṑṓọỏốồổỗộsśŝşšșṡṣṥṧṩuùúûüũūŭůűųǔǖǘǚǜȕȗṳṵṷṹṻụủxẋẍzźżžẑẓẕ
  latin_d: dƌďđǆǳḋḍḏḑḓ
  latin_f: fƒḟ
  latin_g: gĝğġģǧǵḡ
  latin_i: iìíîïĩīĭįıĳǐȉȋḭḯỉị
  latin_j: jĵǰȷɉ
  latin_l: lĺļľŀłƚǉḷḹḻḽⱡ
  latin_ơ: ơớờởỡợ
  latin_p: pṕṗ
  latin_q: qƞ
  latin_r: rŕŗřȑȓṙṛṝṟ
  latin_t: tţťŧțṫṭṯṱẗ
  latin_ư: ưứừửữự
  latin_v: vṽṿ
  latin_w: wŵẁẃẅẇẉẘ
  latin_y: yýÿŷȳẏẙỳỵỷỹ
  period: .,

templates:
  latin_A,latin_T: -1
  latin_A,latin_V: -1
  latin_A,latin_W: -1
  latin_A,latin_Y: -1
  latin_A,latin_f: -1
  latin_A,latin_j: -1
  latin_A,latin_l: -1
  latin_A,latin_t: -1
  latin_A,latin_v: -1
  latin_A,latin_w: -1
  latin_F,latin_A: -1
  latin_F,latin_Æ: -1
  latin_F,latin_a: -1
  latin_F,latin_cemnosuxz: -1
  latin_F,latin_d: -1
  latin_F,latin_f: -1
  latin_F,latin_g: -1
  latin_F,latin_i: -1
  latin_F,latin_j: -1
  latin_F,latin_ơ: -1
  latin_F,latin_p: -1
  latin_F,latin_q: -1
  latin_F,latin_r: -1
  latin_F,latin_t: -1
  latin_F,latin_ư: -1
  latin_F,latin_v: -1
  latin_F,latin_w: -1
  latin_F,latin_y: -1
  latin_F,period: -1
  latin_L,latin_T: -1
  latin_L,latin_V: -1
  latin_L,latin_W: -1
  latin_L,latin_Y: -1
  latin_L,latin_f: -1
  latin_L,latin_j: -1
  latin_L,latin_l: -1
  latin_L,latin_t: -1
  latin_L,latin_v: -1
  latin_L,latin_w: -1
  latin_L,latin_y: -1
  latin_P,latin_A: -1
  latin_P,latin_Æ: -1
  latin_P,latin_a: -1
  latin_P,period: -1
  latin_T,latin_A: -1
  latin_T,latin_Æ: -1
  latin_T,latin_a: -1
  latin_T,latin_cemnosuxz: -1
  latin_T,latin_d: -1
  latin_T,latin_f: -1
  latin_T,latin_i: -1
  latin_T,latin_j: -1
  latin_T,latin_ơ: -1
  latin_T,latin_p: -1
  latin_T,latin_q: -1
  latin_T,latin_r: -1
  latin_T,latin_t: -1
  latin_T,latin_ư: -1
  latin_T,latin_v: -1
  latin_T,latin_w: -1
  latin_T,latin_y: -1
  latin_T,period: -1
  latin_Ư,latin_A: -1
  latin_Ư,latin_Æ: -1
  latin_Ư,latin_a: -1
  latin_Ư,latin_cemnosuxz: -1
  latin_Ư,latin_d: -1
  latin_Ư,latin_f: -1
  latin_Ư,latin_i: -1
  latin_Ư,latin_j: -1
  latin_Ư,latin_ơ: -1
  latin_Ư,latin_p: -1
  latin_Ư,latin_q: -1
  latin_Ư,latin_r: -1
  latin_Ư,latin_t: -1
  latin_Ư,latin_ư: -1
  latin_Ư,latin_v: -1
  latin_Ư,latin_w: -1
  latin_Ư,latin_y: -1
  latin_Ư,period: -1
  latin_V,latin_A: -1
  latin_V,latin_Æ: -1
  latin_V,latin_a: -1
  latin_V,latin_cemnosuxz: -1
  latin_V,latin_d: -1
  latin_V,latin_f: -1
  latin_V,latin_g: -1
  latin_V,latin_i: -1
  latin_V,latin_j: -1
  latin_V,latin_ơ: -1
  latin_V,latin_p: -1
  latin_V,latin_q: -1
  latin_V,latin_r: -1
  latin_V,latin_t: -1
  latin_V,latin_ư: -1
  latin_V,latin_v: -1
  latin_V,latin_w: -1
  latin_V,latin_y: -1
  latin_V,period: -1
  latin_W,latin_A: -1
  latin_W,latin_Æ: -1
  latin_W,latin_a: -1
  latin_W,latin_cemnosuxz: -1
  latin_W,latin_d: -1
  latin_W,latin_f: -1
  latin_W,latin_g: -1
  latin_W,latin_i: -1
  latin_W,latin_j: -1
  latin_W,latin_ơ: -1
  latin_W,latin_p: -1
  latin_W,latin_q: -1
  latin_W,latin_r: -1
  latin_W,latin_t: -1
  latin_W,latin_ư: -1
  latin_W,latin_v: -1
  latin_W,latin_w: -1
  latin_W,latin_y: -1
  latin_W,period: -1
  latin_Y,latin_A: -1
  latin_Y,latin_Æ: -1
  latin_Y,latin_a: -1
  latin_Y,latin_cemnosuxz: -1
  latin_Y,latin_d: -1
  latin_Y,latin_f: -1
  latin_Y,latin_g: -1
  latin_Y,latin_i: -1
  latin_Y,latin_j: -1
  latin_Y,latin_ơ: -1
  latin_Y,latin_p: -1
  latin_Y,latin_q: -1
  latin_Y,latin_r: -1
  latin_Y,latin_t: -1
  latin_Y,latin_ư: -1
  latin_Y,latin_v: -1
  latin_Y,latin_w: -1
  latin_Y,latin_y: -1
  latin_Y,period: -1
  latin_f,latin_a: -1
  latin_f,period: -1
  latin_i,latin_j: -1
  latin_l,latin_j: -1
  latin_ơ,latin_a: -1
  latin_ơ,period: -1
  latin_r,latin_a: -1
  latin_r,period: -1
  latin_ư,latin_a: -1
  latin_ư,latin_cemnosuxz: -1
  latin_ư,period: -1
  latin_v,period: -1
  latin_w,period: -1
  latin_y,period: -1
