name: Build Fonts

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.11

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Build fonts
      run: python ./build.py --parallel --log INFO

    - name: Compress build directory
      run: zip -r build.zip build/

    - name: Upload build.zip
      uses: actions/upload-artifact@v2
      with:
        name: build.zip
        path: build.zip

